class PacketType 
{
    constructor(name = "", id = 0)
    {
        this.name = name;
        this.id = id;
    }

    toString()
    {
        return this.name+" Packet: "+this.id;
    }

    getId()
    {
        return this.id;
    }

    static Login = new PacketType("Login", 2);
    static HumanVisual = new PacketType("HumanVisual", 3);
    static KeepAlive = new PacketType("KeepAlive", 4);
    static Vehicles = new PacketType("Vehicles", 5);
    static PlayerConnect = new PacketType("PlayerConnect", 6);
    static VehiclesUnreliable = new PacketType("VehiclesUnreliable", 7);
    static MetaGrid = new PacketType("MetaGrid", 9);
    static Helicopter = new PacketType("Helicopter", 11);
    static SyncIsoObject = new PacketType("SyncIsoObject", 12);
    static PlayerTimeout = new PacketType("PlayerTimeout", 13);
    static SteamGeneric = new PacketType("SteamGeneric", 14);
    static PassengerMap = new PacketType("PassengerMap", 16);
    static AddItemToMap = new PacketType("AddItemToMap", 17);
    static SentChunk = new PacketType("SentChunk", 18);
    static SyncClock = new PacketType("SyncClock", 19);
    static AddInventoryItemToContainer = new PacketType("AddInventoryItemToContainer", 20);
    static ConnectionDetails = new PacketType("ConnectionDetails", 21);
    static RemoveInventoryItemFromContainer = new PacketType("RemoveInventoryItemFromContainer", 22);
    static RemoveItemFromSquare = new PacketType("RemoveItemFromSquare", 23);
    static RequestLargeAreaZip = new PacketType("RequestLargeAreaZip", 24);
    static Equip = new PacketType("Equip", 25);
    static HitCharacter = new PacketType("HitCharacter", 26);
    static AddCoopPlayer = new PacketType("AddCoopPlayer", 27);
    static WeaponHit = new PacketType("WeaponHit", 28);
    static KillZombie = new PacketType("KillZombie", 30); // Deprecated
    static SandboxOptions = new PacketType("SandboxOptions", 31);
    static SmashWindow = new PacketType("SmashWindow", 32);
    static PlayerDeath = new PacketType("PlayerDeath", 33);
    static RequestZipList = new PacketType("RequestZipList", 34);
    static ItemStats = new PacketType("ItemStats", 35);
    static NotRequiredInZip = new PacketType("NotRequiredInZip", 36);
    static RequestData = new PacketType("RequestData", 37);
    static GlobalObjects = new PacketType("GlobalObjects", 38);
    static ZombieDeath = new PacketType("ZombieDeath", 39);
    static AccessDenied = new PacketType("AccessDenied", 40);
    static PlayerDamage = new PacketType("PlayerDamage", 41);
    static Bandage = new PacketType("Bandage", 42);
    static EatFood = new PacketType("EatFood", 43);
    static RequestItemsForContainer = new PacketType("RequestItemsForContainer", 44);
    static Drink = new PacketType("Drink", 45);
    static SyncAlarmClock = new PacketType("SyncAlarmClock", 46);
    static PacketCounts = new PacketType("PacketCounts", 47);
    static SendModData = new PacketType("SendModData", 48);
    static RemoveContestedItemsFromInventory = new PacketType("RemoveContestedItemsFromInventory", 49);
    static ScoreboardUpdate = new PacketType("ScoreboardUpdate", 50);
    static ReceiveModData = new PacketType("ReceiveModData", 51);
    static ServerQuit = new PacketType("ServerQuit", 52);
    static PlaySound = new PacketType("PlaySound", 53);
    static WorldSound = new PacketType("WorldSound", 54);
    static AddAmbient = new PacketType("AddAmbient", 55);
    static SyncClothing = new PacketType("SyncClothing", 56);
    static ClientCommand = new PacketType("ClientCommand", 57);
    static ObjectModData = new PacketType("ObjectModData", 58);
    static ObjectChange = new PacketType("ObjectChange", 59);
    static BloodSplatter = new PacketType("BloodSplatter", 60);
    static ZombieSound = new PacketType("ZombieSound", 61);
    static ZombieDescriptors = new PacketType("ZombieDescriptors", 62);
    static SlowFactor = new PacketType("SlowFactor", 63);
    static Weather = new PacketType("Weather", 64);
    static RequestPlayerData = new PacketType("RequestPlayerData", 67); // Deprecated
    static RemoveCorpseFromMap = new PacketType("RemoveCorpseFromMap", 68);
    static AddCorpseToMap = new PacketType("AddCorpseToMap", 69);
    static BecomeCorpse = new PacketType("BecomeCorpse", 70);
    static StartFire = new PacketType("StartFire", 75);
    static UpdateItemSprite = new PacketType("UpdateItemSprite", 76);
    static StartRain = new PacketType("StartRain", 77);
    static StopRain = new PacketType("StopRain", 78);
    static WorldMessage = new PacketType("WorldMessage", 79);
    static getModData = new PacketType("getModData", 80);
    static ReceiveCommand = new PacketType("ReceiveCommand", 81);
    static ReloadOptions = new PacketType("ReloadOptions", 82);
    static Kicked = new PacketType("Kicked", 83);
    static ExtraInfo = new PacketType("ExtraInfo", 84);
    static AddItemInInventory = new PacketType("AddItemInInventory", 85);
    static ChangeSafety = new PacketType("ChangeSafety", 86);
    static Ping = new PacketType("Ping", 87);
    static WriteLog = new PacketType("WriteLog", 88); // Deprecated
    static AddXP = new PacketType("AddXP", 89);
    static UpdateOverlaySprite = new PacketType("UpdateOverlaySprite", 90);
    static Checksum = new PacketType("Checksum", 91);
    static ConstructedZone = new PacketType("ConstructedZone", 92);
    static RegisterZone = new PacketType("RegisterZone", 94);
    static WoundInfection = new PacketType("WoundInfection", 97); // Deprecated
    static Stitch = new PacketType("Stitch", 98);
    static Disinfect = new PacketType("Disinfect", 99);
    static AdditionalPain = new PacketType("AdditionalPain", 100); // Deprecated
    static RemoveGlass = new PacketType("RemoveGlass", 101);
    static Splint = new PacketType("Splint", 102);
    static RemoveBullet = new PacketType("RemoveBullet", 103);
    static CleanBurn = new PacketType("CleanBurn", 104);
    static SyncThumpable = new PacketType("SyncThumpable", 105);
    static SyncDoorKey = new PacketType("SyncDoorKey", 106);
    static AddXpCommand = new PacketType("AddXpCommand", 107); // Deprecated
    static AddXpCommand = new PacketType("AddXpCommand", 107);
    static Teleport = new PacketType("Teleport", 108);
    static RemoveBlood = new PacketType("RemoveBlood", 109);
    static AddExplosiveTrap = new PacketType("AddExplosiveTrap", 110);
    static BodyDamageUpdate = new PacketType("BodyDamageUpdate", 112);
    static SyncSafehouse = new PacketType("SyncSafehouse", 114);
    static SledgehammerDestroy = new PacketType("SledgehammerDestroy", 115);
    static StopFire = new PacketType("StopFire", 116);
    static Cataplasm = new PacketType("Cataplasm", 117);
    static AddAlarm = new PacketType("AddAlarm", 118);
    static PlaySoundEveryPlayer = new PacketType("PlaySoundEveryPlayer", 119);
    static SendCustomColor = new PacketType("SendCustomColor", 121);
    static SyncCompost = new PacketType("SyncCompost", 122);
    static ChangePlayerStats = new PacketType("ChangePlayerStats", 123);
    static AddXpFromPlayerStatsUI = new PacketType("AddXpFromPlayerStatsUI", 124); // Deprecated
    static SyncXP = new PacketType("SyncXP", 126);
    static PacketTypeShort = new PacketType("PacketTypeShort", 127); // Deprecated
    static Userlog = new PacketType("Userlog", 128);
    static AddUserlog = new PacketType("AddUserlog", 129);
    static RemoveUserlog = new PacketType("RemoveUserlog", 130);
    static AddWarningPoint = new PacketType("AddWarningPoint", 131);
    static MessageForAdmin = new PacketType("MessageForAdmin", 132);
    static WakeUpPlayer = new PacketType("WakeUpPlayer", 133);
    static SendTransactionID = new PacketType("SendTransactionID", 134); // Deprecated
    static GetDBSchema = new PacketType("GetDBSchema", 135);
    static GetTableResult = new PacketType("GetTableResult", 136);
    static ExecuteQuery = new PacketType("ExecuteQuery", 137);
    static ChangeTextColor = new PacketType("ChangeTextColor", 138);
    static SyncNonPvpZone = new PacketType("SyncNonPvpZone", 139);
    static SyncFaction = new PacketType("SyncFaction", 140);
    static SendFactionInvite = new PacketType("SendFactionInvite", 141);
    static AcceptedFactionInvite = new PacketType("AcceptedFactionInvite", 142);
    static AddTicket = new PacketType("AddTicket", 143);
    static ViewTickets = new PacketType("ViewTickets", 144);
    static RemoveTicket = new PacketType("RemoveTicket", 145);
    static RequestTrading = new PacketType("RequestTrading", 146);
    static TradingUIAddItem = new PacketType("TradingUIAddItem", 147);
    static TradingUIRemoveItem = new PacketType("TradingUIRemoveItem", 148);
    static TradingUIUpdateState = new PacketType("TradingUIUpdateState", 149);
    static SendItemListNet = new PacketType("SendItemListNet", 150); // Deprecated
    static ChunkObjectState = new PacketType("ChunkObjectState", 151);
    static ReadAnnotedMap = new PacketType("ReadAnnotedMap", 152);
    static RequestInventory = new PacketType("RequestInventory", 153);
    static SendInventory = new PacketType("SendInventory", 154);
    static InvMngReqItem = new PacketType("InvMngReqItem", 155);
    static InvMngGetItem = new PacketType("InvMngGetItem", 156);
    static InvMngRemoveItem = new PacketType("InvMngRemoveItem", 157);
    static StartPause = new PacketType("StartPause", 158);
    static StopPause = new PacketType("StopPause", 159);
    static TimeSync = new PacketType("TimeSync", 160);
    static SyncIsoObjectReq = new PacketType("SyncIsoObjectReq", 161); // Deprecated
    static PlayerSave = new PacketType("PlayerSave", 162); // Deprecated
    static SyncWorldObjectsReq = new PacketType("SyncWorldObjectsReq", 163); // Deprecated
    static SyncObjects = new PacketType("SyncObjects", 164); // Deprecated
    static SendPlayerProfile = new PacketType("SendPlayerProfile", 166);
    static LoadPlayerProfile = new PacketType("LoadPlayerProfile", 167);
    static SpawnRegion = new PacketType("SpawnRegion", 171);
    static PlayerDamageFromCarCrash = new PacketType("PlayerDamageFromCarCrash", 172);
    static PlayerAttachedItem = new PacketType("PlayerAttachedItem", 173);
    static ZombieHelmetFalling = new PacketType("ZombieHelmetFalling", 174);
    static AddBrokenGlass = new PacketType("AddBrokenGlass", 175);
    static SyncPerks = new PacketType("SyncPerks", 177);
    static SyncWeight = new PacketType("SyncWeight", 178);
    static SyncInjuries = new PacketType("SyncInjuries", 179);
    static SyncEquippedRadioFreq = new PacketType("SyncEquippedRadioFreq", 181);
    static InitPlayerChat = new PacketType("InitPlayerChat", 182);
    static PlayerJoinChat = new PacketType("PlayerJoinChat", 183);
    static PlayerLeaveChat = new PacketType("PlayerLeaveChat", 184);
    static ChatMessageFromPlayer = new PacketType("ChatMessageFromPlayer", 185);
    static ChatMessageToPlayer = new PacketType("ChatMessageToPlayer", 186);
    static PlayerStartPMChat = new PacketType("PlayerStartPMChat", 187);
    static AddChatTab = new PacketType("AddChatTab", 189);
    static RemoveChatTab = new PacketType("RemoveChatTab", 190);
    static PlayerConnectedToChat = new PacketType("PlayerConnectedToChat", 191);
    static PlayerNotFound = new PacketType("PlayerNotFound", 192);
    static SendSafehouseInvite = new PacketType("SendSafehouseInvite", 193);
    static AcceptedSafehouseInvite = new PacketType("AcceptedSafehouseInvite", 194);
    static ClimateManagerPacket = new PacketType("ClimateManagerPacket", 200);
    static IsoRegionServerPacket = new PacketType("IsoRegionServerPacket", 201);
    static IsoRegionClientRequestFullUpdate = new PacketType("IsoRegionClientRequestFullUpdate", 202);
    static EventPacket = new PacketType("EventPacket", 210);
    static Statistic = new PacketType("Statistic", 211);
    static StatisticRequest = new PacketType("StatisticRequest", 212);
    static PlayerUpdateReliable = new PacketType("PlayerUpdateReliable", 213);
    static ActionPacket = new PacketType("ActionPacket", 214);
    static ZombieControl = new PacketType("ZombieControl", 215);
    static PlayWorldSound = new PacketType("PlayWorldSound", 216);
    static StopSound = new PacketType("StopSound", 217);
    static PlayerUpdate = new PacketType("PlayerUpdate", 218);
    static ZombieSimulation = new PacketType("ZombieSimulation", 219);
    static PingFromClient = new PacketType("PingFromClient", 220);
    static ZombieSimulationReliable = new PacketType("ZombieSimulationReliable", 221);
    static EatBody = new PacketType("EatBody", 222);
    static Thump = new PacketType("Thump", 223);
    static SyncRadioData = new PacketType("SyncRadioData", 224);
    static LoginQueueRequest2 = new PacketType("LoginQueueRequest2", 225);
    static LoginQueueDone2 = new PacketType("LoginQueueDone2", 226);
    static ItemTransaction = new PacketType("ItemTransaction", 227);
    static KickOutOfSafehouse = new PacketType("KickOutOfSafehouse", 211);
    static SneezeCough = new PacketType("SneezeCough", 229);
    static BurnCorpse = new PacketType("BurnCorpse", 230);

    // Two-byte integers
    static WaveSignal = new PacketType("WaveSignal", 300);
    static PlayerListensChannel = new PacketType("PlayerListensChannel", 301);
    static RadioServerData = new PacketType("RadioServerData", 302);
    static RadioDeviceDataState = new PacketType("RadioDeviceDataState", 303);
    static SyncCustomLightSettings = new PacketType("SyncCustomLightSettings", 304);
    static ReplaceOnCooked = new PacketType("ReplaceOnCooked", 305);
    static GlobalModData = new PacketType("GlobalModData", 32000);
    static GlobalModDataRequest = new PacketType("GlobalModDataRequest", 32001);
    static RadioPostSilenceEvent = new PacketType("RadioPostSilenceEvent", 32002);
}

module.exports = { PacketType }